services:
  apache:
    build:
      dockerfile: .docker/Dockerfile
      context: .
    container_name: test-php
    command: php app/artisan serve --host=0.0.0.0 --port=8000
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    depends_on:
      - mysqldb
    links:
      - mysqldb
  mysqldb:
    container_name: test-mysqldb
    image: mysql:5.7
    ports:
      - '3307:3306'
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
      - ./.docker/logs/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dbtest
  phpmyadmin:
    container_name: test-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysqldb
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1